connected
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    doc_ref.set({"action":STOP, "time": 0})
  File "/usr/local/lib/python3.7/dist-packages/firebase_admin/db.py", line 264, in set
    self._client.request('put', self._add_suffix(), json=value, params='print=silent')
  File "/usr/local/lib/python3.7/dist-packages/firebase_admin/db.py", line 929, in request
    return super(_Client, self).request(method, url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/firebase_admin/_http_client.py", line 118, in request
    resp = self._session.request(method, self.base_url + url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/google/auth/transport/requests.py", line 476, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/usr/local/lib/python3.7/dist-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/service_account.py", line 411, in refresh
    request, self._token_uri, assertion
  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 193, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 165, in _token_endpoint_request
    _handle_error_response(response_data)
  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_data)
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.'})
